# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end
  config.vm.synced_folder "..", "/vagrant", disabled: true
  config.vm.synced_folder "../", "/vagrant/php_tool/", owner: "vagrant", group: "vagrant", type: "rsync", rsync__exclude: %w(src)
  config.vm.provision "shell", inline: <<-SHELL
  sudo su
  apt-get update -y
  apt-get install -y --no-install-recommends \
    python \
    python3 \
    python-pip \
    python3-pip \
    python3-bpfcc \
    python-bpfcc \
    sysvinit-utils \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg2 \
    git \
    software-properties-common

  curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
  add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
  apt-get update -y
  apt-get install -y --no-install-recommends \
    docker-ce \
    docker-ce-cli \
    docker-compose \
    containerd.io

  usermod -aG docker vagrant
  docker info

  echo "deb http://deb.debian.org/debian sid main non-free" >> /etc/apt/sources.list.d/bcc-install.list
  echo "deb-src http://deb.debian.org/debian sid main non-free" >> /etc/apt/sources.list.d/bcc-install.list
  echo "deb http://httpredir.debian.org/debian/ buster main non-free" >> /etc/apt/sources.list.d/bcc-install.list
  echo "deb-src http://httpredir.debian.org/debian/ buster main non-free" >> /etc/apt/sources.list.d/bcc-install.list
  echo "deb http://security.debian.org/ buster/updates main non-free" >> /etc/apt/sources.list.d/bcc-install.list
  echo "deb-src http://security.debian.org/ buster/updates main non-free" >> /etc/apt/sources.list.d/bcc-install.list
  echo "deb http://ftp.us.debian.org/debian/ buster-updates main non-free" >> /etc/apt/sources.list.d/bcc-install.list
  echo "deb-src http://ftp.us.debian.org/debian/ buster-updates main non-free" >> /etc/apt/sources.list.d/bcc-install.list
  echo "deb http://debug.mirrors.debian.org/debian-debug/ unstable-debug main" >> /etc/apt/sources.list.d/bcc-install.list

  apt-get update -y && apt-get install -y \
	debhelper \
	cmake \
	llvm-dev \
	libclang-dev \
	libelf-dev \
	bison \
	flex \
	libedit-dev \
	clang-format \
	python \
	python-netaddr \
	python-pyroute2 \
	luajit \
	libluajit-5.1-dev \
	arping \
	iperf \
	ethtool \
	devscripts \
	zlib1g-dev \
	libfl-dev \
	netperfmeter \
	netperf \
	dh-python \
	libllvm6.0 llvm-6.0-dev libclang-6.0-dev \
	systemtap-sdt-dev \
    --no-install-recommends

  SHELL
end
